# Generated by Django 2.1.5 on 2019-02-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190225_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, height_field='375px', upload_to='post_pics', width_field='365px'),
        ),
    ]
